services:
  - type: web
    name: rasa-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && rasa train
    startCommand: rasa run --enable-api --cors "*" --port 10000
    envVars:
      - key: PORT
        value: 10000
    runtime:
      python_version: 3.8
